DROP TABLE IF EXISTS UPLOADER;
CREATE TABLE IF NOT EXISTS UPLOADER (
	user_id INTEGER NOT NULL,
	password VARCHAR(10) NOT NULL,
	fname VARCHAR(15) NOT NULL,
	lname VARCHAR(15) NOT NULL,
	email VARCHAR(25) NOT NULL,
	phone INTEGER(10) NOT NULL,
	company_afm INTEGER DEFAULT NULL,
	PRIMARY KEY (user_id),
	CONSTRAINT UPLOADER_fk0 FOREIGN KEY (company_afm) REFERENCES MESITIKI(afm)
);
DROP TABLE IF EXISTS AGGELIA;
CREATE TABLE IF NOT EXISTS AGGELIA (
	ad_id INTEGER NOT NULL,
	publisher_id INTEGER NOT NULL,
	type VARCHAR(15) NOT NULL,
	location VARCHAR(255) NOT NULL,
	purpose VARCHAR(10) NOT NULL,
	price INTEGER NOT NULL,
	contact_number INTEGER DEFAULT 6900000000,
	publication_date DATE DEFAULT NULL,
	title VARCHAR(255) NOT NULL,
	description VARCHAR(255) DEFAULT '...',
	image_src VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (ad_id),
	CONSTRAINT AGGELIA_fk0 FOREIGN KEY (publisher_id) REFERENCES UPLOADER(user_id) ON DELETE CASCADE
	--CONSTRAINT AGG_PURP CHECK(purpose IN ('buy','rent'))
);

DROP TABLE IF EXISTS XARAKTIRISTIKO;
CREATE TABLE IF NOT EXISTS XARAKTIRISTIKO (
	code INTEGER NOT NULL,
	name VARCHAR(25) NOT NULL,
	PRIMARY KEY (code)
);
DROP TABLE IF EXISTS ENDIAFEROMENOS;
CREATE TABLE IF NOT EXISTS ENDIAFEROMENOS (
	user_id INTEGER NOT NULL,
	password VARCHAR(10) NOT NULL,
	fname VARCHAR(15) NOT NULL,
	lname VARCHAR(15) NOT NULL,
	email VARCHAR(25) NOT NULL,
	phone INTEGER(10) NOT NULL,
	afm INTEGER DEFAULT NULL,
	PRIMARY KEY (user_id)
);
DROP TABLE IF EXISTS SXOLIO;
CREATE TABLE IF NOT EXISTS SXOLIO (
	ad_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	comment VARCHAR(255) DEFAULT "...",
	comm_date DATE NOT NULL,
	rating INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (ad_id,user_id)
	CONSTRAINT SXOLIO_fk0 FOREIGN KEY (ad_id) REFERENCES AGGELIA(ad_id) ON DELETE CASCADE
);
DROP TABLE IF EXISTS PROTIMISI;
CREATE TABLE IF NOT EXISTS PROTIMISI (
	user_id INTEGER NOT NULL,
	location VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	purpose VARCHAR(10) NOT NULL,
	PRIMARY KEY (user_id,location,type,purpose),
	CONSTRAINT PROTIMISI_fk0 FOREIGN KEY (user_id) REFERENCES ENDIAFEROMENOS(user_id) ON DELETE CASCADE
);
DROP TABLE IF EXISTS PAREXEI;
CREATE TABLE IF NOT EXISTS PAREXEI (
	ad_id INTEGER NOT NULL,
	char_code INTEGER NOT NULL,
	value VARCHAR(25) NOT NULL,
	PRIMARY KEY (ad_id,char_code),
	CONSTRAINT PAREXEI_fk0 FOREIGN KEY (ad_id) REFERENCES AGGELIA(ad_id) ON DELETE CASCADE,
	CONSTRAINT PAREXEI_fk1 FOREIGN KEY (char_code) REFERENCES XARAKTIRISTIKO(code) ON DELETE CASCADE ON UPDATE CASCADE
);
DROP TABLE IF EXISTS AGAPIMENA;
CREATE TABLE IF NOT EXISTS AGAPIMENA (
	user_id INTEGER NOT NULL,
	ad_id INTEGER NOT NULL,
	PRIMARY KEY (user_id,ad_id),
	CONSTRAINT AGAPIMENA_fk0 FOREIGN KEY (ad_id) REFERENCES AGGELIA(ad_id) ON DELETE CASCADE,
	CONSTRAINT AGAPIMENA_fk1 FOREIGN KEY (user_id) REFERENCES ENDIAFEROMENOS(user_id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS MESITIKI;
CREATE TABLE IF NOT EXISTS MESITIKI (
	afm INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL,
	PRIMARY KEY (afm)
);
